# Generated by Django 3.2 on 2021-04-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meet',
        ),
        migrations.AddField(
            model_name='user',
            name='meet_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='meets.meets'),
            preserve_default=False,
        ),
    ]
