# Generated by Django 3.2 on 2021-04-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
        ('accounts', '0002_auto_20210424_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meets.meets'),
        ),
    ]
